---
- name: "Check status: {{ plugin }}"
  ansible.builtin.uri:
    url: "http://127.0.0.1:2113/info/plugins?format=json"
    method: GET
    return_content: true
    body_format: json
  register: result
  until: "result.json[plugin][instance]['status']|default('') == 'INSTANCE_STATUS_CODE_OK'"
  retries: 12
  delay: 5

- name: "Print plugin Status Code: {{ plugin }}"
  ansible.builtin.debug:
    var: result.json[plugin][instance]['status']
