---
- name: Include variable file
  include_vars:
    file: dbo_mapping.yml
  tags:
    - dbo

- name: PRINT output
  debug:
    var: "dbo_plugin"
  tags:
    - dbo

- name: Expected plugins
  set_fact:
    expected_plugins: "{{ dbo_mapping[dbo_plugin['databaseType']] }}"
  tags:
    - dbo

- name: PRINT expected plugins
  debug:
    var: "expected_plugins"
  tags:
    - dbo

- name: Read output of headless installer
  slurp:
    src: '{{ uams_local_pkg_path }}/output.json'
  register: output
  tags:
    - dbo

- name: Parse JSON content
  set_fact:
    entities: "{{ output.content | b64decode | from_json | dict2items }}"
  tags:
    - dbo

- name: PRINT entities
  debug:
    var: entities
  tags:
    - dbo

- name: DBO Plugins to be verified
  debug:
    msg: "Plugin name {{ item[0] }}, instance {{ item[1]['key'] | trim('e-') }}"
  with_nested:
    - '{{ expected_plugins }}'
    - '{{ entities }}'
  tags:
    - dbo

- name: "Check DBO plugins status"
  vars:
    plugin: "{{ item[0] }}"
    instance: "{{ item[1]['key'] | trim('e-') }}"
  ansible.builtin.uri:
    url: "http://127.0.0.1:2113/info/plugins?format=json"
    method: GET
    return_content: true
    body_format: json
  register: result
  until: "result.json[plugin][instance]['status_code']|default('') == 'STATUS_CODE_OK'"
  retries: 2
  delay: 1
  with_nested:
    - '{{ expected_plugins }}'
    - '{{ entities }}'
  tags:
    - dbo