---
# TBR
- name: Print dbAgents content
  debug:
    var: dbAgents
  tags:
    - dbo

- name: Create destination directory
  ansible.builtin.file:
    path: '{{ uams_local_pkg_path }}'
    mode: '0755'
    state: directory
  tags:
    - dbo

- name: Download installation package
  ansible.builtin.get_url:
    url: '{{ dbo_headless_installer_url }}'
    dest: '{{ uams_local_pkg_path }}/dbo-headless-installer.zip'
    mode: '440'
  tags:
    - dbo

- name: Create destination directory for headless installer
  ansible.builtin.file:
    path: '{{ uams_local_pkg_path }}/headless-installer'
    mode: '0755'
    state: directory
  tags:
    - dbo

- name: Unarchive a DBO headless installer
  ansible.builtin.unarchive:
#    src: dbo-headless-installer.zip
    src: '{{ uams_local_pkg_path }}/dbo-headless-installer.zip'
    dest: '{{ uams_local_pkg_path }}/headless-installer'
# Change this to unpack downloaded archive not one from master
    remote_src: yes
  tags:
    - dbo

- name: Load uamsclient ID file
  ansible.builtin.slurp:
    src: /opt/solarwinds/uamsclient/var/uamsclientid
  register: file_content
  tags:
    - dbo

- name: Decode uamsclient ID
  set_fact:
    uamsclientid: "{{ file_content.content | b64decode }}"
  tags:
    - dbo
    -
# TBR
- name: Print dbAgents content
  debug:
    var: uamsclientid
  tags:
    - dbo

- name: Template a file to /etc/file.conf
  ansible.builtin.template:
    src: templates/dbo.j2
    dest: '{{ uams_local_pkg_path }}/input.json'
#    owner: bin
#    group: wheel
    mode: '0644'
  tags:
    - dbo

- name: Template a file to /etc/file.conff
  ansible.builtin.template:
    src: templates/dbo_swo_params.j2
    dest: '{{ uams_local_pkg_path }}/swoparams.json'
#    owner: bin
#    group: wheel
    mode: '0644'
  tags:
    - dbo

- name: Run the binary with parameters using command module
  command: '{{ uams_local_pkg_path }}/headless-installer/bin/linux-amd64/dbo-headless-installer -swoparams {{ uams_local_pkg_path }}/swoparams.json -onboard-databases {{ uams_local_pkg_path }}/input.json'
  register: result_command
  tags:
    - dbo

- name: Display the result from command module
  debug:
    var: result_command
  tags:
    - dbo
