---
- name: Create local_config.yaml file for Linux systems
  ansible.builtin.template:
    src: templates/managed_locally.j2
    dest: "/opt/solarwinds/uamsclient/var/local_config.yaml"
    mode: "0644"
  when: ansible_facts['system'] == "Linux"
  become: true

- name: Create local_config.yaml file for Windows systems
  ansible.builtin.template:
    src: templates/managed_locally.j2
    dest: "C:\\ProgramData\\SolarWinds\\UAMSClient\\local_config.yaml"
    mode: "0644"
  when: ansible_facts['system'] == "Windows"
