---
- name: Check if OS is supported
  ansible.builtin.fail:
    msg: "{{ unsupported_os_msg }}"
  when: ansible_facts.os_family not in ['RedHat', 'Debian', 'Windows', 'Rocky']

- name: Check RedHat version
  ansible.builtin.fail:
    msg: "{{ unsupported_os_version_msg }}"
  when:
    - ansible_facts.distribution == 'RedHat'
    - ansible_facts.distribution_major_version|int < 7

- name: Check Amazon version
  ansible.builtin.fail:
    msg: "{{ unsupported_os_version_msg }}"
  when:
    - ansible_facts.distribution == 'Amazon'
    - ansible_facts.distribution_major_version|int < 2

- name: Check Rocky version
  ansible.builtin.fail:
    msg: "{{ unsupported_os_version_msg }}"
  when:
    - ansible_facts.distribution == 'Rocky'
    - ansible_facts.distribution_major_version|int < 8

- name: Check CentOS version
  ansible.builtin.fail:
    msg: "{{ unsupported_os_version_msg }}"
  when:
    - ansible_facts.distribution == 'CentOS'
    - ansible_facts.distribution_major_version|int < 7

- name: Check Debian version
  ansible.builtin.fail:
    msg: "{{ unsupported_os_version_msg }}"
  when:
    - ansible_facts.distribution == 'Debian'
    - ansible_facts.distribution_major_version|int < 9

- name: Check Fedora version
  ansible.builtin.fail:
    msg: "{{ unsupported_os_version_msg }}"
  when:
    - ansible_facts.distribution == 'Fedora'
    - ansible_facts.distribution_major_version|int < 32

- name: Check Ubuntu version
  ansible.builtin.fail:
    msg: "{{ unsupported_os_version_msg }}"
  when:
    - ansible_facts.distribution == 'Ubuntu'
    - ansible_facts.distribution_major_version|int < 18

- name: Check Oracle Linux version
  ansible.builtin.fail:
    msg: "{{ unsupported_os_version_msg }}"
  when:
    - ansible_facts.distribution == 'OracleLinux'
    - ansible_facts.distribution_major_version|int < 8

- name: Check Kali version
  ansible.builtin.fail:
    msg: "{{ unsupported_os_version_msg }}"
  when:
    - ansible_facts.distribution == 'Kali'
    - ansible_facts.distribution_major_version|int < 2021
