---
- name: Validate 'UAMS_ACCESS_TOKEN' environment variable
  ansible.builtin.fail:
    msg: Environment variable 'UAMS_ACCESS_TOKEN' is not set.
  when: ansible_env.UAMS_ACCESS_TOKEN == ""

- name: Validate 'SWO_URL' environment variable
  ansible.builtin.fail:
    msg: Environment variable 'UAMS_SWO_URL' is not set.
  when: ansible_env.SWO_URL == ""
